# Strategy parameters per symbol

# Refined strategy for BTCUSD (and ETHUSD)
BTCUSD_CONFIG = {
    "MAX_WATCHLIST_SIZE": 3,
    "MAX_POI_DISTANCE_PCT": 0.02,
    "MIN_POI_DISTANCE_PCT": 0.002,
    "MERGE_THRESHOLD_PCT": 0.0005,
    "SWING_STRENGTH_PCT": 0.002,
    "EXPIRY_CANDLES": 10,
    "EXPIRY_DISTANCE_PCT": 0.005,

    "CONFIRMATION_MAX_CANDLES": 3,
    "CONFIRMATION_MAX_DISTANCE_PCT": 0.002,
    "CONFIRMATION_ENGULFING_CLOSE_BEYOND_POI": True,
    "CONFIRMATION_REJECTION_MIN_BODY_WICK_RATIO": 1.5,
    "CONFIRMATION_SWEEP_RECLAIM_CLOSE_BEYOND_POI": True,

    "VOLATILITY_MIN_ATR_PCT": 0.002,
    "VOLATILITY_ATR_PERIOD": 20,

    "MIN_RR_FOR_TP1": 1.0,

    "USE_15M_POI_FILTER": True,

    "ANTI_FLIP_COOLDOWN_MINUTES": 0,
}

# ETHUSD uses the same config as BTCUSD
ETHUSD_CONFIG = BTCUSD_CONFIG.copy()

# Strategy for XAUUSD (unchanged)
XAUUSD_CONFIG = {
    "MAX_WATCHLIST_SIZE": 3,
    "MAX_POI_DISTANCE_PCT": 0.02,
    "MIN_POI_DISTANCE_PCT": 0.002,
    "MERGE_THRESHOLD_PCT": 0.0005,
    "SWING_STRENGTH_PCT": 0.002,
    "EXPIRY_CANDLES": 10,
    "EXPIRY_DISTANCE_PCT": 0.005,

    "CONFIRMATION_MAX_CANDLES": 5,
    "CONFIRMATION_MAX_DISTANCE_PCT": 0.002,
    "CONFIRMATION_ENGULFING_CLOSE_BEYOND_POI": False,
    "CONFIRMATION_REJECTION_MIN_BODY_WICK_RATIO": 1.5,
    "CONFIRMATION_SWEEP_RECLAIM_CLOSE_BEYOND_POI": False,

    "VOLATILITY_MIN_ATR_PCT": 0.001,
    "VOLATILITY_ATR_PERIOD": 20,

    "MIN_RR_FOR_TP1": 1.2,

    "USE_15M_POI_FILTER": False,

    "ANTI_FLIP_COOLDOWN_MINUTES": 0,
}